console.log("*****Before Initialization*****");
var bankName = typeof SBIBank;
console.log("Value Of bankName variable is:", typeof SBIBank);
console.log("type of bankName variable is:", typeof SBIBank);
console.log("*****After Intialization*****");
var myBankName = "SBIBank";
console.log("Value Of myBankName variable is:", myBankName);
console.log("type of myBankName variable is:", typeof myBankName);
console.log("*****String Data type*****");
var marks = '90%';
console.log("Value Of marks variable is:", marks);
console.log("type of marks variable is:", typeof marks);
console.log("*****seperate Daclatation and Initilization*****");
console.log("*****Declaration*****");
var isWorking = typeof yes;
console.log("value of isWorking variable is:", typeof yes); 
console.log("******Initialization******");
var isWorking = typeof true;
console.log("value of isWorking variable is:", true);
console.log("******Type of variable*****");
console.log("type of isWorking variable is:", typeof true);
console.log("*****Declaration and Initialization variable on Same Line*****");
var totleCount ='Hundred and Seven';
console.log("value of totleCount variable is:",  totleCount);
console.log("type of totleCount variable is:", typeof totleCount);
console.log("******After Updating the totalCount******");
var totalCount= 107;
console.log("value of totleCount variable is:", 107);
console.log("type of totleCount variable is:", typeof 107);

